# Changes here will be overwritten by Copier
_commit: v0.0.91
_src_path: gh:LabAutomationAndScreening/copier-base-template.git
description: Creating libraries in the VueJS ecosystem
install_claude_cli: false
python_ci_versions:
- 3.13.2
python_version: 3.13.2
repo_name: copier-vue-package-template
repo_org_name: LabAutomationAndScreening
repo_org_name_for_copyright: LabAutomationAndScreening
ssh_port_number: 51211
template_might_want_to_install_aws_ssm_port_forwarding_plugin: false
template_uses_javascript: true
template_uses_pulumi: false
template_uses_python: false
template_uses_vuejs: true

