# Changes here will be overwritten by Copier
_commit: v0.0.128-3-gcb8b702
_src_path: gh:LabAutomationAndScreening/copier-base-template.git
copier_answers_directory: .
description: Creating libraries in the VueJS ecosystem
install_claude_cli: true
python_ci_versions:
- 3.13.9
python_version: 3.13.9
repo_name: copier-vue-package-template
repo_org_name: LabAutomationAndScreening
repo_org_name_for_copyright: LabAutomationAndScreening
ssh_port_number: 51211
template_might_want_to_install_aws_ssm_port_forwarding_plugin: false
template_publishes_releases: false
template_uses_pulumi: false
template_uses_python: false
template_uses_typescript: true
template_uses_vuejs: true

