[project]
name = "copier-vue-package-template"
version = "0.1.0"
description = "Creating libraries in the VueJS ecosystem"
readme = "README.md"
requires-python = ">=3.13.9"
dependencies = [
    # Specific to this template


    # Managed by upstream template
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "pytest-randomly>=4.1.0",
    "pyright[nodejs]>=1.1.409",
    "ty>=0.0.40",
    "copier==9.15.1",
    "copier-template-extensions==0.3.3"
]

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple/"
exclude-newer = "1 day"
