# adapted from https://github.com/copier-org/copier-template-extensions#context-hook-extension
from typing import Any
from typing import override

from copier_template_extensions import ContextHook


class ContextUpdater(ContextHook):
    update = False

    @override
    def hook(self, context: dict[Any, Any]) -> dict[Any, Any]:
        context["uv_version"] = "0.9.18"
        context["pnpm_version"] = "10.25.0"
        context["pre_commit_version"] = "4.5.0"
        context["pyright_version"] = ">=1.1.407"
        context["pytest_version"] = ">=9.0.2"
        context["pytest_randomly_version"] = ">=4.0.1"
        context["pytest_cov_version"] = ">=7.0.0"
        context["ty_version"] = ">=0.0.2"
        context["copier_version"] = "==9.11.0"
        context["copier_template_extensions_version"] = "==0.3.3"
        context["sphinx_version"] = "9.0.4"
        context["pulumi_version"] = ">=3.212.0"
        context["pulumi_aws_version"] = ">=7.14.0"
        context["pulumi_aws_native_version"] = ">=1.40.0"
        context["pulumi_command_version"] = ">=1.1.3"
        context["pulumi_github_version"] = ">=6.9.1"
        context["pulumi_okta_version"] = ">=6.2.0"
        context["boto3_version"] = ">=1.42.11"
        context["ephemeral_pulumi_deploy_version"] = ">=0.0.5"
        context["pydantic_version"] = ">=2.12.5"
        context["pyinstaller_version"] = "6.17.0"
        context["setuptools_version"] = "80.7.1"
        context["strawberry_graphql_version"] = ">=0.287.0"
        context["fastapi_version"] = ">=0.124.2"
        context["fastapi_offline_version"] = ">=1.7.4"
        context["uvicorn_version"] = ">=0.38.0"
        context["lab_auto_pulumi_version"] = ">=0.1.17"
        context["ariadne_codegen_version"] = ">=0.17.0"
        context["pytest_mock_version"] = "3.15.1"
        context["uuid_utils_version"] = ">=0.12.0"
        context["syrupy_version"] = ">=5.0.0"
        context["structlog_version"] = ">=25.5.0"
        context["httpx_version"] = "0.28.1"
        context["python_kiota_bundle_version"] = ">=1.9.7"
        context["vcrpy_version"] = ">=8.1.0"
        context["pytest_recording_version"] = ">=0.13.4"
        context["pytest_asyncio_version"] = ">=1.3.0"

        context["node_version"] = "24.11.1"
        context["nuxt_ui_version"] = "^4.2.1"
        context["nuxt_version"] = "^4.2.2"
        context["nuxt_icon_version"] = "^2.1.0"
        context["typescript_version"] = "^5.9.3"
        context["playwright_version"] = "^1.57.0"
        context["vue_version"] = "^3.5.25"
        context["vue_tsc_version"] = "^3.1.2"
        context["vue_devtools_api_version"] = "^8.0.0"
        context["vue_router_version"] = "^4.6.0"
        context["dotenv_cli_version"] = "^11.0.0"
        context["faker_version"] = "^10.1.0"
        context["vitest_version"] = "^3.2.4"
        context["eslint_version"] = "~9.38.0"
        context["nuxt_eslint_version"] = "^1.10.0"
        context["zod_version"] = "^4.1.12"
        context["zod_from_json_schema_version"] = "^0.5.1"
        context["types_node_version"] = "^25.0.0"
        context["nuxt_apollo_version"] = "5.0.0-alpha.15"
        context["graphql_codegen_cli_version"] = "^6.0.0"
        context["graphql_codegen_typescript_version"] = "^5.0.0"
        context["graphql_codegen_typescript_operations_version"] = "^5.0.0"
        context["graphql_tools_mock_version"] = "^9.1.0"
        context["tailwindcss_version"] = "^4.1.11"
        context["iconify_vue_version"] = "^5.0.0"
        context["iconify_json_lucide_version"] = "^1.2.71"
        context["nuxt_fonts_version"] = "^0.12.1"
        context["nuxtjs_color_mode_version"] = "^3.5.2"
        context["vue_test_utils_version"] = "^2.4.6"
        context["nuxt_test_utils_version"] = "3.19.1"
        context["vue_eslint_parser_version"] = "^10.1.3"
        context["happy_dom_version"] = "^20.0.2"
        context["node_kiota_bundle_version"] = "1.0.0-preview.99"

        context["gha_checkout"] = "v6.0.1"
        context["gha_setup_python"] = "v6.1.0"
        context["gha_cache"] = "v4.3.0"
        context["gha_upload_artifact"] = "v5.0.0"
        context["gha_download_artifact"] = "v6.0.0"
        context["gha_github_script"] = "v7.0.1"
        context["gha_setup_buildx"] = "v3.11.1"
        context["buildx_version"] = "v0.27.0"
        context["gha_docker_build_push"] = "v6.18.0"
        context["gha_configure_aws_credentials"] = "v5.1.1"
        context["gha_amazon_ecr_login"] = "v2.0.1"
        context["gha_setup_node"] = "v6.1.0"
        context["gha_action_gh_release"] = "v2.2.1"
        context["gha_mutex"] = "1ebad517141198e08d47cf72f3c0975316620a65 # v1.0.0-alpha.10"
        context["gha_pypi_publish"] = "v1.13.0"
        context["gha_sleep"] = "v2.0.3"
        context["gha_linux_runner"] = "ubuntu-24.04"
        context["gha_windows_runner"] = "windows-2025"
        context["gha_short_timeout_minutes"] = "2"
        context["gha_medium_timeout_minutes"] = "8"
        context["gha_long_timeout_minutes"] = "15"
        context["gha_xlong_timeout_minutes"] = "45"

        context["debian_release_name"] = "bookworm"
        context["alpine_image_version"] = "3.23"
        context["nginx_image_version"] = "1.29.4"

        context["kiota_cli_version"] = "1.29.0"

        context["py312_version"] = "3.12.7"
        context["py313_version"] = "3.13.2"
        context["py314_version"] = "3.14.0"

        # Kludge to be able to help symlinked jinja files in the child and grandchild templates
        context["template_uses_vuejs"] = True
        context["template_uses_javascript"] = True
        return context
