/*
 * ============== WARNING ==============================================================================
 * File is managed by copier template: gh:LabAutomationAndScreening/copier-base-template.git
 * See .config/.copier-managed-files.json for details.
 *
 * You are welcome to make changes to this file in your repo if they are custom to your project,
 * but if the change should be shared with other projects, please backport it to the template repo.
 * =====================================================================================================
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import vitest from "@vitest/eslint-plugin";

// Consumers render this file at different depths below the repo root, so no fixed number of `../`
// reaches `.config/eslint-rules/` for all of them.
function findLocalRulesDir() {
  let dir = path.dirname(fileURLToPath(import.meta.url));
  for (;;) {
    const candidate = path.join(dir, ".config", "eslint-rules");
    if (fs.statSync(candidate, { throwIfNoEntry: false })?.isDirectory() === true) return candidate;
    if (fs.existsSync(path.join(dir, ".git"))) {
      throw new Error(`Could not find .config/eslint-rules under the project root ${dir}`);
    }
    const parent = path.dirname(dir);
    if (parent === dir) {
      throw new Error(`Could not find .config/eslint-rules above ${import.meta.url}`);
    }
    dir = parent;
  }
}

async function loadLocalRules() {
  const rulesDir = findLocalRulesDir();
  const entries = fs.readdirSync(rulesDir).filter((entry) => entry.endsWith(".mjs"));
  const rules = {};
  for (const entry of entries) {
    const ruleName = entry.slice(0, -".mjs".length);
    const module = await import(pathToFileURL(path.join(rulesDir, entry)).href);
    if (module.default === undefined) {
      throw new Error(`Local ESLint rule module ${entry} has no default export`);
    }
    rules[ruleName] = module.default;
  }
  return rules;
}

const localRules = await loadLocalRules();

/** @type {import("eslint").Linter.Config} */
export const istanbulIgnoreIfMustThrowConfig = {
  files: ["**/*.{ts,vue}"],
  plugins: {
    local: {
      rules: localRules,
    },
  },
  rules: {
    "local/istanbul-ignore-if-must-throw": "error",
  },
};

export const ignoresConfig = {
  ignores: [
    "**/generated/**", // ignore linting autogenerated files
    ".claude/**", // Claude folder often contains 3rd party scripts
  ],
};

/** @type {import("eslint").Linter.Config} */
export const vueScriptLangConfig = {
  // Disallow <script lang="js"> in Vue files
  files: ["**/*.vue"],
  rules: {
    "vue/block-lang": [
      "error",
      {
        script: {
          lang: "ts",
        },
      },
    ],
  },
};

/** @type {import("eslint").Linter.Config} */
export const noJsConfig = {
  // Disallow .js files in favor of typescript
  files: ["**/*.js"],
  rules: {
    "no-restricted-syntax": [
      "error",
      {
        selector: "Program",
        message: "Use .ts instead of .js.",
      },
    ],
  },
};

/** @type {import("eslint").Linter.Config} */
export const vitestConfig = {
  files: ["**/*.{test,spec}.ts"],
  plugins: {
    vitest,
  },
  rules: {
    ...Object.fromEntries(
      // @vitest/eslint-plugin's configs.all sets every rule to "warn"; promote them to "error" (preserving the
      // plugin's intentional "off" defaults) so violations fail lint. Done programmatically so rules added in future
      // plugin versions are promoted too, rather than silently arriving as warnings.
      Object.entries(vitest.configs.all.rules).map(([rule, severity]) =>
        severity === "off" ? [rule, "off"] : [rule, "error"],
      ),
    ),
    "vitest/max-expects": ["error", { max: 10 }], // 5 is too low. There are legitimate reasons to have several assertions (especially with DOM tests) that share the same Arrange/Act
    "vitest/unbound-method": "off", // requires typed linting (parserOptions.project), not configured in this project
    "vitest/require-mock-type-parameters": "off", // stylistic; vi.fn() inferred type is sufficient and explicit generics add noise on trivial mocks
    "vitest/prefer-describe-function-title": "off", // autofix rewrites string titles to identifier references, which then conflicts with vitest/valid-title for default-imported functions
    "vitest/padding-around-all": "off", // project test style keeps blank lines minimal (see AGENTS.md); these rules pad every block boundary
    "vitest/padding-around-after-all-blocks": "off",
    "vitest/padding-around-after-each-blocks": "off",
    "vitest/padding-around-before-all-blocks": "off",
    "vitest/padding-around-before-each-blocks": "off",
    "vitest/padding-around-describe-blocks": "off",
    "vitest/padding-around-expect-groups": "off",
    "vitest/padding-around-test-blocks": "off",
    "vitest/no-focused-tests": ["error", { fixable: false }], // automatically fixing this could confuse the user
    "vitest/consistent-test-filename": ["error", { pattern: ".*\\.spec\\.ts$" }],
    "vitest/prefer-lowercase-title": "off", // no reason to force lowercase titles
    "vitest/consistent-test-it": "off", // consistency for this is overrated, let the dev choose what's most readable based on the test title
    "vitest/prefer-to-be-falsy": "off", // sometimes you want to check explicitly for false and not just falsy
    "vitest/prefer-to-be-truthy": "off", // sometimes you want to check explicitly for true and not just truthy
  },
};

/** @type {import("eslint").Linter.Config} */
export const e2eConfig = {
  // E2E specs run under the @playwright/test runner,
  // importing test/expect from tests/e2e/fixtures, not vitest. The broad **/*.{test,spec}.ts block
  // above still attaches the vitest plugin, so disable the rules that misfire on Playwright specs.
  files: ["tests/e2e/**/*.spec.ts"],
  rules: {
    "vitest/prefer-expect-assertions": "off", // Playwright's web-first matchers; vitest's expect.assertions() counter can't track them
    "vitest/prefer-importing-vitest-globals": "off", // test/expect come from Playwright via fixtures; autofix would inject a conflicting vitest import
    "vitest/require-hook": "off", // top-level setup (e.g. destructuring shared constants) is normal in Playwright specs
  },
};

export const sharedConfigs = [
  ignoresConfig,
  vueScriptLangConfig,
  noJsConfig,
  vitestConfig,
  e2eConfig,
  istanbulIgnoreIfMustThrowConfig,
];
